Fix/streamline (#14)
* asdf

* asdf

* asdf

* asdf

* asdf

* asdf

* asdf

* asdf

* asdf

* feat: added conventional commit message hook

* chore: commented hook

* chore: updated hook

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,6 +1,6 @@
 #!/bin/sh
 if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
+    echo -e "\e[31mAborting commit. Your commit message is invalid.\e[0m" >&2
     exit 1
 fi
 
